# Generated by Django 4.0.5 on 2022-06-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='skill_rating',
            field=models.TextField(max_length=250),
        ),
    ]
