# Generated by Django 4.0.5 on 2022-06-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_projects_project_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='jihad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('living_country', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=250)),
                ('email_add', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='personal',
            name='profession',
            field=models.CharField(max_length=250),
        ),
    ]
