# Generated by Django 4.0.5 on 2022-06-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_jihad_alter_personal_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jihad',
            name='email_add',
            field=models.EmailField(max_length=250),
        ),
    ]
